'''fruits=["orange","apple","pear","banana","kiwi"]
print(fruits.count("apple"))
fruits.sort()
print(fruits)'''
numbers=[3,5,1,9,10]
#numbers.sort()
#print(numbers)
print(sorted(numbers))
print(numbers)